"""empty message

Revision ID: b886245b58b6
Revises: 27401773ef3c
Create Date: 2023-08-13 18:05:15.540889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b886245b58b6'
down_revision = '27401773ef3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prompt', ['prompt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
